<script setup>
import { motion } from 'motion-v'
import { MessageSquare, Paperclip, GripVertical, Calendar } from 'lucide-vue-next'
import { projects } from '../../stores/projects'
import { due, calendar, initials } from '../../utils/format'
defineProps({ task: Object, draggable: Boolean })
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches
</script>
<template><motion.button :initial="{ opacity: reducedMotion ? 1 : 0 }" :animate="{ opacity: 1 }" :transition="{ duration: reducedMotion ? 0 : 0.12 }" type="button" :class="['task-card',task.priority.toLowerCase()]" :aria-label="`Open task ${task.title}`" @click="projects.openTask(task.id)"><div class="task-card-top"><span :class="['priority', task.priority.toLowerCase()]"><i></i>{{ task.priority }}</span><span class="task-number">TF-{{ task.id }}<GripVertical v-if="draggable" class="drag-handle" :size="15" aria-label="Drag task" /></span></div><span v-if="task.blocked" class="blocked-label">Blocked</span><h3>{{ task.title }}</h3><p v-if="task.description" class="task-description">{{ task.description }}</p><div class="task-card-progress"><div class="progress-track"><span :style="{width:`${task.progress}%`}"></span></div><span>{{ task.progress }}%</span></div><div class="task-card-bottom"><span class="mini-person" :title="task.assignee?.name || 'Unassigned'"><span class="avatar avatar-tiny">{{ initials(task.assignee?.name) }}</span><span>{{ task.assignee?.name || 'Unassigned' }}</span></span><span v-if="task.deadline" :class="['task-deadline',{overdue:due(task)==='Overdue'}]" :title="`${calendar(task.deadline)} · ${due(task)}`"><Calendar :size="12" />{{ calendar(task.deadline).replace(/,? \d{4}$/, '') }}</span></div><div v-if="task.comment_count || task.attachment_count" class="task-counts"><span v-if="task.comment_count"><MessageSquare :size="12" />{{ task.comment_count }}</span><span v-if="task.attachment_count"><Paperclip :size="12" />{{ task.attachment_count }}</span></div></motion.button></template>
