<script setup>
import { ref, reactive, watch } from 'vue'
import Dialog from 'primevue/dialog'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Checkbox from 'primevue/checkbox'
import { api } from '../../services/api'
import { projects } from '../../stores/projects'
import { workspace } from '../../stores/workspace'
import { development as dev } from '../../stores/development'
const form=reactive({}),busy=ref(false),error=ref(''),file=ref(),result=ref('')
watch(()=>dev.state.settings,open=>{if(open){Object.assign(form,dev.state.config);error.value=''}})
async function save(){busy.value=true;error.value='';try{await api.put(`/projects/${projects.state.activeId}/development`,form);await dev.load();dev.state.settings=false}catch(e){error.value=e.friendly}finally{busy.value=false}}
async function upload(){if(!file.value || busy.value)return;busy.value=true;error.value='';result.value='';try{const data=new FormData();data.append('file',file.value);const response=await api.post(`/projects/${projects.state.activeId}/workspace/import`,data);result.value=`Imported ${response.data.files} files across ${response.data.nodes} nodes.`;await workspace.tree();await dev.load();await projects.refresh()}catch(e){error.value=e.friendly}finally{busy.value=false}}
</script>
<template>
<Dialog v-model:visible="dev.state.settings" modal header="Project development" :style="{width:'590px'}" :breakpoints="{'640px':'95vw'}"><form class="form-stack" @submit.prevent="save"><p>Commands run against a fresh copy of the latest saved project files. Changes made by a process do not overwrite online files.</p><label for="run-command">Run command</label><InputText id="run-command" v-model="form.run_command" placeholder="python app.py" maxlength="500"/><label for="test-command">Test command</label><InputText id="test-command" v-model="form.test_command" placeholder="python -m pytest" maxlength="500"/><label for="working-directory">Working directory</label><InputText id="working-directory" v-model="form.working_directory" placeholder="."/><div v-if="dev.state.suggestions.run_command || dev.state.suggestions.test_command" class="suggestion-box"><strong>Detected suggestions</strong><span>{{ dev.state.suggestions.run_command }} · {{ dev.state.suggestions.test_command }}</span><Button label="Use suggestions" text @click="Object.assign(form,{run_command:dev.state.suggestions.run_command,test_command:dev.state.suggestions.test_command})"/></div><label class="inline-check"><Checkbox v-model="form.allow_edit_execution" binary/> Allow members with EDIT on every workspace node to execute</label><p class="field-hint">Local execution supports Python scripts, pytest and unittest. It has a 120-second limit and blocks ordinary access outside the temporary project/runtime, child processes and networking. Use only trusted code: this is not a production sandbox. npm, interactive stdin and preview servers are not supported.</p><p v-if="!dev.state.enabled" class="field-hint">Execution is disabled on this server. See README for trusted local setup.</p><p v-if="error" role="alert" class="form-error">{{ error }}</p><Button label="Save configuration" type="submit" :loading="busy"/></form></Dialog>
<Dialog v-model:visible="dev.state.importDialog" modal header="Import existing project" :style="{width:'510px'}" :breakpoints="{'560px':'95vw'}" :closable="!busy"><div class="form-stack"><p>Import into an empty workspace. Existing files are never overwritten. Choose a ZIP of source files and assets, up to 10 MB compressed, 25 MB expanded and 1,000 nodes. Each file may be up to 512 KiB. Exclude dependency directories. Binary assets are preserved and downloadable.</p><label for="project-zip">Project ZIP</label><input id="project-zip" type="file" accept=".zip" :disabled="busy" @change="file=$event.target.files[0];result='';error=''"/><span v-if="file">{{ file.name }} · {{ (file.size/1024).toFixed(1) }} KiB</span><p v-if="error" role="alert" class="form-error">{{ error }}</p><p v-if="result" role="status" class="success-message">{{ result }}</p><Button label="Import project" :loading="busy" :disabled="!file || !!result" @click="upload"/></div></Dialog>
</template>
