<script setup>
import { computed } from 'vue'
import { projects } from '../../stores/projects'
import { session } from '../../stores/session'
import { useRouter } from 'vue-router'
const router=useRouter(),d=computed(()=>projects.state.dashboard),leader=computed(()=>session.state.team.role==='LEADER')
const tasks=computed(()=>Object.fromEntries(projects.state.tasks.map(t=>[t.id,t])))
const mine=computed(()=>projects.state.tasks.filter(t=>t.assigned_to===session.state.user.id))
function openRisk(r){if(r.task_id)projects.openTask(r.task_id);else router.push('/team')}
</script>
<template><div v-if="d?.health" class="insights-grid"><template v-if="leader"><section class="panel health-panel"><span class="eyebrow">PROJECT HEALTH</span><div class="health-score"><strong>{{ d.health.score }}<small>/100</small></strong><span>{{ d.health.label }}</span></div><p>{{ d.blocked }} blocked tasks · Rule-based assessment</p><details><summary>Why this score?</summary><p>Starts at 100. Deductions use real overdue, blocked, urgent and approaching-deadline proportions, workload and remaining critical-path time.</p><div v-for="reason in d.health.deductions" :key="reason.label">−{{ reason.points }} · {{ reason.label }}</div></details></section><section class="panel risk-panel"><span class="eyebrow">ATTENTION NEEDED</span><h2>Risks & next actions</h2><button v-for="(risk,i) in d.risks" :key="i" class="risk-row" @click="openRisk(risk)"><strong>{{ risk.label }}</strong><span>{{ risk.title }}</span></button><p v-if="!d.risks.length" class="field-hint">No rule-based risks detected in the current project data.</p></section><section class="panel critical-panel"><span class="eyebrow">CRITICAL PATH</span><h2>{{ d.critical_path.remaining_days }} estimated working days remaining</h2><p class="field-hint">Longest remaining dependency chain. Progress reduces duration; completed tasks contribute zero. Unestimated tasks assume 1 working day. This is a planning estimate, without calendar/resource scheduling.</p><div class="dependency-chain"><template v-for="(id,index) in d.critical_path.task_ids" :key="id"><span v-if="index" aria-hidden="true">→</span><button :class="{blocked:tasks[id]?.blocked}" @click="projects.openTask(id)"><small>TF-{{ id }}</small>{{ tasks[id]?.title }}<em v-if="tasks[id]?.blocked">Blocked</em></button></template><p v-if="!d.critical_path.task_ids.length">No unfinished critical work.</p></div><details><summary>All dependency connections</summary><div v-for="edge in d.critical_path.edges" :key="`${edge.from_id}-${edge.to_id}`" class="dependency-edge"><button @click="projects.openTask(edge.from_id)">{{ tasks[edge.from_id]?.title }}</button><span>→</span><button @click="projects.openTask(edge.to_id)">{{ tasks[edge.to_id]?.title }}</button></div><p v-if="!d.critical_path.edges.length">No dependencies configured.</p></details></section></template><section v-else class="panel member-focus"><span class="eyebrow">YOUR FOCUS</span><h2>{{ mine.filter(t=>t.status!=='DONE').length }} tasks to move forward</h2><button v-for="t in mine" :key="t.id" class="risk-row" @click="projects.openTask(t.id)"><strong>{{ t.title }}</strong><span>{{ t.progress }}% · {{ t.blocked?'Blocked by prerequisites':t.status.replaceAll('_',' ') }} · {{ t.deadline || 'No deadline' }}</span></button><p v-if="!mine.length">No tasks assigned to you yet.</p></section></div></template>
